### ISSUE TITLE
在andriod 虚拟机上错误码为9

### ISSUE THREAD

**Issue by mynameisenthusiasm** [sisong/HDiffPatch#236]
在ios中生成diff文件后，通过so在安卓上调用，错误代码为9，是否是大小端的问题？
![image](https://user-images.githubusercontent.com/54618402/127815338-bf6ceccb-1e63-4f0b-b020-f4d704f71cd6.png)
这两台虚拟机都报错9，但是真机上为0

**Comment by sisong** [comment]
这些代码在x86虚拟机上跑过的， 而且arm真机和x86都是小端机器，所以和虚拟机、大小端都没有关系。    
返回值类型是THPatchResult，9是HPATCH_HDIFFINFO_ERROR；   看起来是读取到的数据有误？

**Comment by mynameisenthusiasm** [comment]
感谢大佬回复！是的，我之前试图看源码没有很懂，都是用的您提供的so和binary去运行的，是用adb在安卓和电脑之间传输文件，我再看看源码分析一下，diff选择的应该是hdiff那个？我没有添加任何参数，只输入了新旧文件名去跑，您的新的格式指的是什么，就是用的您release里面的。。。

**Comment by mynameisenthusiasm** [comment]
我好像有点线索了，应该还是权限的问题？因为有一个线索就是在mac上没给应用开权限也显示的是kill 9

**Comment by mynameisenthusiasm** [comment]
有点奇怪呀，请问大佬有测试过最新的版本吗。在真机上确实是0，就是虚拟机是9

**Comment by sisong** [comment]
我重新提交了so文件（见release），应该解决了这个问题

ref #242

**Comment by mynameisenthusiasm** [comment]
不能直接替换的吗😭，我直接换了so文件和java报了个大错
    --------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.myapplication, PID: 2579
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.example.myapplication/com.example.myapplication.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.example.myapplication.MainActivity" on path: DexPathList[[zip file "/data/app/~~oGW8eRBcL9ibToEdwRu_0Q==/com.example.myapplication-yLZ-gP1WUdN5mBRVG_VejQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~oGW8eRBcL9ibToEdwRu_0Q==/com.example.myapplication-yLZ-gP1WUdN5mBRVG_VejQ==/lib/x86, /data/app/~~oGW8eRBcL9ibToEdwRu_0Q==/com.example.myapplication-yLZ-gP1WUdN5mBRVG_VejQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3365)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.example.myapplication.MainActivity" on path: DexPathList[[zip file "/data/app/~~oGW8eRBcL9ibToEdwRu_0Q==/com.example.myapplication-yLZ-gP1WUdN5mBRVG_VejQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~oGW8eRBcL9ibToEdwRu_0Q==/com.example.myapplication-yLZ-gP1WUdN5mBRVG_VejQ==/lib/x86, /data/app/~~oGW8eRBcL9ibToEdwRu_0Q==/com.example.myapplication-yLZ-gP1WUdN5mBRVG_VejQ==/base.apk!/lib/x86, /system/lib, /system_ext/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
I/Process: Sending signal. PID: 2579 SIG: 9

**Comment by mynameisenthusiasm** [comment]
补充目前文件结构：
