### ISSUE TITLE
模拟器合成文件失败

### ISSUE THREAD

**Issue by sun804336516** [sisong/HDiffPatch#242]
模拟器Hpztch合成文件失败，code2

**Comment by sun804336516** [comment]
release的3.1.1的libhpatchz.so

**Comment by sisong** [comment]
2即 HPATCH_OPENREAD_ERROR ，文件读取方式打开失败      
是否是权限或路径问题？   建议将测试文件放在getApplicationContext().getFilesDir().getPath()或其子目录路径

**Comment by sun804336516** [comment]
应该不是权限路径问题，相同的安装包放在手机上，正常合并文件。放在模拟器上报错code=2，放在getApplicationContext().getFilesDir().getPath()或者getCacheDir中，命名能读取到文件，却显示：
2021-08-10 20:06:20.944 14693-14738/io.github.lizhangqu.corepatch.sample E/SnowdreamFramework: 19738373 oldfile：/data/user/0/io.github.lizhangqu.corepatch.sample/cache/WLGamePlugin_19.apk
2021-08-10 20:06:20.944 14693-14738/io.github.lizhangqu.corepatch.sample E/SnowdreamFramework: 5670493 patchFile：/data/user/0/io.github.lizhangqu.corepatch.sample/cache/patch.patch
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err: java.io.FileNotFoundException: /data/user/0/io.github.lizhangqu.corepatch.sample/cache/patch.patch (Permission denied)
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err:     at java.io.FileInputStream.open(Native Method)
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:146)
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.applier.core.CoreAbsApplier.apply(CoreAbsApplier.java:97)
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.sample.MainActivity.hdiffArchivePatcher(MainActivity.java:314)
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.sample.MainActivity.access$100(MainActivity.java:34)
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.sample.MainActivity$5$1.run(MainActivity.java:215)
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err:     at java.lang.Thread.run(Thread.java:761)
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err: io.github.lizhangqu.corepatch.applier.ApplierException: file not exist
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.applier.core.CoreAbsApplier.apply(CoreAbsApplier.java:100)
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.sample.MainActivity.hdiffArchivePatcher(MainActivity.java:314)
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.sample.MainActivity.access$100(MainActivity.java:34)
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.sample.MainActivity$5$1.run(MainActivity.java:215)
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err:     at java.lang.Thread.run(Thread.java:761)
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err: Caused by: java.io.FileNotFoundException: /data/user/0/io.github.lizhangqu.corepatch.sample/cache/patch.patch (Permission denied)
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err:     at java.io.FileInputStream.open(Native Method)
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:146)
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.applier.core.CoreAbsApplier.apply(CoreAbsApplier.java:97)
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err: 	... 4 more

**Comment by sun804336516** [comment]
这个是放在sd卡根目录，能正常获取到文件流,但是报错code=2.这块可能跟模拟器权限有关》？用的是雷电跟mumu模拟器
2021-08-10 20:09:07.331 14843-14881/io.github.lizhangqu.corepatch.sample E/SnowdreamFramework: 19738373 oldfile：/storage/emulated/0/WLGamePlugin_19.apk
2021-08-10 20:09:07.357 14843-14881/io.github.lizhangqu.corepatch.sample E/SnowdreamFramework: 5670493 patchFile：/storage/emulated/0/patch.patch
2021-08-10 20:09:07.359 14843-14881/io.github.lizhangqu.corepatch.sample I/System.out: apply useZip:false
2021-08-10 20:09:07.545 14843-14881/io.github.lizhangqu.corepatch.sample V/libnb: enter native_bridge2_isSupported /data/app/io.github.lizhangqu.corepatch.sample-1/lib/arm/libhpatchz.so
2021-08-10 20:09:07.545 14843-14881/io.github.lizhangqu.corepatch.sample V/libnb: enter native_bridge2_loadLibrary /data/app/io.github.lizhangqu.corepatch.sample-1/lib/arm/libhpatchz.so
2021-08-10 20:09:07.558 14843-14881/io.github.lizhangqu.corepatch.sample D/houdini: [14881] Added shared library /data/app/io.github.lizhangqu.corepatch.sample-1/lib/arm/libhpatchz.so for ClassLoader by Native Bridge.
2021-08-10 20:09:07.558 14843-14881/io.github.lizhangqu.corepatch.sample V/libnb: enter native_bridge2_getTrampoline JNI_OnLoad, trampoline_addr 0x0
2021-08-10 20:09:07.558 14843-14881/io.github.lizhangqu.corepatch.sample V/libnb: enter native_bridge2_getTrampoline Java_com_github_sisong_HPatch_patch, trampoline_addr 0xe9404fc4
2021-08-10 20:09:07.575 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err: java.io.IOException: 合成失败，错误码=2
2021-08-10 20:09:07.575 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at com.github.sisong.AndroidHDiffApplier.applyDelta(AndroidHDiffApplier.java:42)
2021-08-10 20:09:07.575 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at com.google.archivepatcher.applier.AbstractFileByFileV1DeltaApplier.applyDeltaInternal(AbstractFileByFileV1DeltaApplier.java:112)
2021-08-10 20:09:07.575 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at com.google.archivepatcher.applier.AbstractFileByFileV1DeltaApplier.applyDelta(AbstractFileByFileV1DeltaApplier.java:74)
2021-08-10 20:09:07.575 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at com.github.sisong.AndroidHDiffArchivePatchApplier.applyPatchReal(AndroidHDiffArchivePatchApplier.java:33)
2021-08-10 20:09:07.575 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.applier.core.CoreAbsApplier.apply(CoreAbsApplier.java:81)
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.applier.core.CoreAbsApplier.apply(CoreAbsApplier.java:97)
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.sample.MainActivity.hdiffArchivePatcher(MainActivity.java:314)
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.sample.MainActivity.access$100(MainActivity.java:34)
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.sample.MainActivity$5$1.run(MainActivity.java:215)
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at java.lang.Thread.run(Thread.java:761)
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err: io.github.lizhangqu.corepatch.applier.ApplierException: apply failure
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.applier.core.CoreAbsApplier.apply(CoreAbsApplier.java:85)
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.applier.core.CoreAbsApplier.apply(CoreAbsApplier.java:97)
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.sample.MainActivity.hdiffArchivePatcher(MainActivity.java:314)
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.sample.MainActivity.access$100(MainActivity.java:34)
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.sample.MainActivity$5$1.run(MainActivity.java:215)
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at java.lang.Thread.run(Thread.java:761)
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err: Caused by: java.io.IOException: 合成失败，错误码=2
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at com.github.sisong.AndroidHDiffApplier.applyDelta(AndroidHDiffApplier.java:42)
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at com.google.archivepatcher.applier.AbstractFileByFileV1DeltaApplier.applyDeltaInternal(AbstractFileByFileV1DeltaApplier.java:112)
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at com.google.archivepatcher.applier.AbstractFileByFileV1DeltaApplier.applyDelta(AbstractFileByFileV1DeltaApplier.java:74)
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at com.github.sisong.AndroidHDiffArchivePatchApplier.applyPatchReal(AndroidHDiffArchivePatchApplier.java:33)
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err:     at io.github.lizhangqu.corepatch.applier.core.CoreAbsApplier.apply(CoreAbsApplier.java:81)
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample W/System.err: 	... 5 more
2021-08-10 20:09:07.576 14843-14881/io.github.lizhangqu.corepatch.sample E/SnowdreamFramework: 合成失败：apply failure

**Comment by sisong** [comment]
```
patchFile：/data/user/0/io.github.lizhangqu.corepatch.sample/cache/patch.patch
2021-08-10 20:06:20.975 14693-14738/io.github.lizhangqu.corepatch.sample W/System.err: java.io.FileNotFoundException: 
``` 
我觉得还是权限问题，试试提前声明文件访问权限？

**Comment by sun804336516** [comment]
老哥  刚刚试了试，在模拟器中getFilesDir中的测试文件手动赋予了所有权限，不会出现FileNotFound（sd卡根目录中的文件没这个问题）。但合并文件还是会出现code=2的错误，在javad代码中尝试获取文件属性都没问题，创建文件流也没问题，老哥可以下载个mumu模拟器尝试下，应该是必现的，用ApkPatch合并倒是没这个问题。
然后尝试给文件赋予权限：
      oldFile.setExecutable(true);
        oldFile.setReadable(true);
        oldFile.setWritable(true);
        patchFile.setExecutable(true);
        patchFile.setReadable(true);
        patchFile.setWritable(true);
也能获取到这些，
2021-08-11 10:15:56.830 5431-5461/io.github.lizhangqu.corepatch.sample E/HPatch: canExecute:true,canRead:true,canWrite:true,true-19738373 oldfile：/data/user/0/io.github.lizhangqu.corepatch.sample/cache/WLGamePlugin_19.apk
2021-08-11 10:15:56.830 5431-5461/io.github.lizhangqu.corepatch.sample E/HPatch: canExecute:true,canRead:true,canWrite:true,true--5670493 patchFile：/data/user/0/io.github.lizhangqu.corepatch.sample/cache/patch.patch
最终还是code=2

**Comment by sisong** [comment]
我的意思是添加“
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />”

**Comment by sun804336516** [comment]
> 我的意思是添加 `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />`
> 另外，确实有人反映在某些模拟器上文件操作失败

老哥 这个WRITE_EXTERNAL_STORAGE跟6.0的动态权限肯定是处理了呀，app指定的sdk版本也小于android11，所以有点奇怪

**Comment by sun804336516** [comment]
我在c里面加了一些log，最终发现是在file_for_patch.c中的_import_fileSeek64函数返回false，导致code=2

**Comment by sisong** [comment]
嗯，我也试了一下，好像 模拟器上的C库没有fseeko这个函数（回失败）！  而改成fseek就没有问题了 ，晕😵

**Comment by sisong** [comment]
我换了一下android的编译方式也绕过了这个问题。

**Comment by mynameisenthusiasm** [comment]
能不能请问一下“换了一下android的编译方式”具体指的什么，如果用cmake会出现这种问题吗？
